### ISSUE TITLE
Remote File Inclusion Not working

### ISSUE THREAD

**Issue by 0x00-null** [opsxcq/docker-vulnerable-dvwa#20]
The PHP function allow_url_include is not enabled.

![image](https://user-images.githubusercontent.com/10076254/115144447-a1573780-a044-11eb-9bd1-59886b66402f.png)

**Comment by vax-r** [comment]
You need to use docker exec to get inside your dvwa container and change the content of your "php.ini"
set allow_url_include to On

**Comment by vax-r** [comment]
There're several "php.ini" , change the one under php and php5 directories
