### ISSUE TITLE
Docker Version in Docker file is outdated

### ISSUE THREAD

**Issue by arunsk7891** [opsxcq/docker-vulnerable-dvwa#29]
https://github.com/opsxcq/docker-vulnerable-dvwa/blob/master/Dockerfile

The FROM debian:9.2
is causing my Docker Jenkins pipeline to fail with Error :
The error mentions you're using debian:9.2. Consider using a more recent Debian base image, such as debian:stretch, which is a general tag that should provide access to the package repositories.

[91mW: The repository 'http://security.debian.org stretch/updates Release' does not have a Release file.

Could you please update : 
FROM debian:stretch

**Comment by Tato418** [comment]
updated it on my fork
