### ISSUE TITLE
Mysql server failed

### ISSUE THREAD

**Issue by MNWPRO** [opsxcq/docker-vulnerable-dvwa#5]
![image](https://user-images.githubusercontent.com/29529706/33520833-72e7d7f0-d7fd-11e7-8df4-e604a8d1bada.png)

**Comment by mike-bailey** [comment]
(As mentioned elsewhere, it's because of https://github.com/moby/moby/issues/34390)

**Comment by mike-bailey** [comment]
@MNWPRO Did you try running it under aufs

**Comment by MNWPRO** [comment]
i will have a try，and thanks

**Comment by mike-bailey** [comment]
No problem. I ask because it worked for me under aufs and if it does for you as well, the issue is upstream between mysql and Docker, in which case there's nothing to be done at this repo.

**Comment by MNWPRO** [comment]
understand

**Comment by makseemoff** [comment]
Look at this: #3

**Comment by mike-bailey** [comment]
I have a similar Dockerfile that does the step you referenced, and mysql still won't start on it unless aufs

**Comment by ycjcl868** [comment]
me too.

**Comment by mike-bailey** [comment]
@ycjcl868 what happened when you tried it under aufs?

**Comment by IronPillar-Sheng** [comment]
i still failed .and my os is macos 10.13.3

**Comment by mike-bailey** [comment]
@IronPillar-Sheng what happens when you try it under aufs?

**Comment by IronPillar-Sheng** [comment]
![image](https://user-images.githubusercontent.com/43240069/45678509-25816f80-bb69-11e8-96b7-c39cc6b3da35.png)

**Comment by IronPillar-Sheng** [comment]
**junjiesheng@sheng  ~  docker run --rm -it -p 80:80 vulnerables/web-dvwa
[+] Starting mysql...
[FAIL] Starting MySQL database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
[+] Starting apache
[....] Starting web server: apache2AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
. ok
==> /var/log/apache2/access.log <==
tail: unrecognized file system type 0x794c7630 for '/var/log/apache2/access.log'. please report this to bug-coreutils@gnu.org. reverting to polling

==> /var/log/apache2/error.log <==
[Tue Sep 18 09:32:30.036627 2018] [mpm_prefork:notice] [pid 780] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Tue Sep 18 09:32:30.036692 2018] [core:notice] [pid 780] AH00094: Command line: '/usr/sbin/apache2'
tail: unrecognized file system type 0x794c7630 for '/var/log/apache2/error.log'. please report this to bug-coreutils@gnu.org. reverting to polling

==> /var/log/apache2/other_vhosts_access.log <==
tail: unrecognized file system type 0x794c7630 for '/var/log/apache2/other_vhosts_access.log'. please report this to bug-coreutils@gnu.org. reverting to polling**

**Comment by IronPillar-Sheng** [comment]
and i don`t not how to run this image under aufs.😂

**Comment by opsxcq** [comment]
Fixed in 67fb5939f759554b8feec436ad290886e5ae5f37
